# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "docker" do |d|
    d.run "dockerfile/elasticsearch",
      args: "-p 9200:9200 -p 9300:9300 -v '/vagrant:/data'"
  end
end
