#
#-*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network :forwarded_port, :host => 2181, :guest => 2181
  config.vm.network :forwarded_port, :host => 60000, :guest => 60000
  config.vm.network :forwarded_port, :host => 60010, :guest => 60010
  config.vm.network :forwarded_port, :host => 60020, :guest => 60020
  config.vm.network :forwarded_port, :host => 60030, :guest => 60030
  config.vm.provision "docker" do |d|
    d.run "mdodsworth/hbase",
      args: "-p 2181:2181 -p 60000:60000 -p 60010:60010 -p 60020:60020 -p 60030:60030 -v '/vagrant/data:/data'"
  end
end

