# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.provision "docker",
      images: ["ubuntu"]

  # expose the docker ephemeral ports
  (49000..49900).each do |port|
      config.vm.network :forwarded_port, :host => port, :guest => port
   end
end
